# Generated by Django 2.2.9 on 2020-02-01 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='name',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=2000)),
                ('second_name', models.CharField(max_length=2000)),
                ('prediction', models.CharField(default='loosu', max_length=2000)),
            ],
        ),
    ]
