# Generated by Django 2.2.9 on 2020-01-27 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flamesSite', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='names',
            new_name='name',
        ),
    ]
